import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {createReadinessServer,publicStatus} from './readiness-live-server.mjs';
const snapshot=()=>({schemaVersion:1,checkedAt:new Date().toISOString(),validForSeconds:300,sites:{chann:{state:'unknown'},buyin:{state:'logged_in'}},component:'ready',base:{read:'granted',write:'unknown'},token:'secret',run:{state:'paused',actualLanes:0,targetLanes:10,completed:10,total:45,reason:'secret',reasonCode:'BASE_READ_UNAVAILABLE'}});
test('public projection omits credentials/free text and preserves true check time',()=>{const s=snapshot(),p=publicStatus(s);assert.equal(p.checkedAt,s.checkedAt);assert(!JSON.stringify(p).includes('secret'));assert.equal(p.run.reason,'飞书名单读取暂未完成');assert.throws(()=>publicStatus({...s,component:'secret'}));});
test('local server restricts routes/origin, starts probe, deduplicates and returns changing snapshots',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'koc-readiness-'));const statusPath=path.join(dir,'status.json'),htmlPath=path.join(dir,'index.html');await fs.writeFile(statusPath,JSON.stringify(snapshot()));await fs.writeFile(htmlPath,'<h1>KOC</h1>');let calls=0,release;const server=createReadinessServer({statusPath,htmlPath,port:18766,refresh:()=>{calls++;return new Promise(r=>release=r)}});await new Promise(r=>server.listen(18766,'127.0.0.1',r));const root='http://127.0.0.1:18766';try{await new Promise(r=>setTimeout(r,15));assert.equal(calls,1);assert.equal((await fetch(root+'/status')).status,200);assert.equal((await fetch(root+'/secret')).status,404);assert.equal((await fetch(root+'/status',{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await fetch(root+'/refresh',{method:'POST'})).status,403);const req=()=>fetch(root+'/refresh',{method:'POST',headers:{Origin:root,'X-KOC-Refresh':'1'}});const a=req(),b=req();await new Promise(r=>setTimeout(r,30));assert.equal(calls,1);release();assert.equal((await a).status,200);assert.equal((await b).status,200);const s=snapshot();s.run.completed=11;await fs.writeFile(statusPath,JSON.stringify(s));assert.equal((await(await fetch(root+'/status')).json()).run.completed,11);
const badHost=await new Promise((resolve,reject)=>{http.get(root+'/status',{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode)}).on('error',reject)});assert.equal(badHost,403);
}finally{release?.();await new Promise(r=>server.close(r));await fs.rm(dir,{recursive:true,force:true})}});
test('live ledger reads latest counts, validates owner PID, blocks traversal and keeps preparation time independent',async()=>{
 const {readLiveRun}=await import('./readiness-live-server.mjs');const root=await fs.mkdtemp(path.join(os.tmpdir(),'koc-ledger-'));const base=path.join(root,'daily-inventory'),dir=path.join(base,'run-2026-10-08T00-00-00-000Z'),lockDir=path.join(root,'contact-canary-original-20260923');await fs.mkdir(dir,{recursive:true});await fs.mkdir(lockDir);await fs.writeFile(path.join(base,'active.json'),JSON.stringify({id:path.basename(dir)}));let ledger={status:'running',entries:[{complete:true,writeState:'verified',readbackVerified:true},{state:'in_flight'},{state:'pending'}]};const save=()=>fs.writeFile(path.join(dir,'ledger.json'),JSON.stringify(ledger));await save();await fs.writeFile(path.join(lockDir,'production.lock'),JSON.stringify({pid:process.pid,mode:'daily-inventory'}));try{let r=await readLiveRun(root);assert.equal(r.state,'running');assert.equal(r.completed,1);assert.equal(r.inFlight,1);assert.equal(r.actualLanes,1);ledger.cooldown={nextEligibleAt:Date.now()+300000};await save();r=await readLiveRun(root);assert.equal(r.state,'cooldown');assert.equal(r.nextProbeAt,ledger.cooldown.nextEligibleAt);await fs.writeFile(path.join(lockDir,'production.lock'),JSON.stringify({pid:0,mode:'daily-inventory'}));assert.equal((await readLiveRun(root)).state,'paused');await fs.writeFile(path.join(base,'active.json'),JSON.stringify({id:'../../secret'}));await assert.rejects(readLiveRun(root),/invalid active/);}finally{await fs.rm(root,{recursive:true,force:true})}
});
test('result categories partition verified, failed, uncertain and pending entries',async()=>{const {summarizeResults}=await import('./readiness-live-server.mjs');const good=outcome=>({outcome,complete:true,writeState:'verified',readbackVerified:true});assert.deepEqual(summarizeResults([good('success'),good('not_shown'),good('no_match'),good('forbidden_by_platform'),{state:'failed'},{state:'uncertain'},{state:'pending'}]),{success:1,not_shown:1,no_match:1,forbidden_by_platform:1,technicalFailure:1,unknownWrite:1,pending:1});assert.throws(()=>publicStatus({...snapshot(),run:{...snapshot().run,results:{success:45}}}),/invalid result counts/)});
test('source summary binds newest batch and requires readback before claiming complete',async()=>{const {readSourceUpdate}=await import('./readiness-live-server.mjs');const root=await fs.mkdtemp(path.join(os.tmpdir(),'koc-source-ui-'));try{const batch='20261008T014711Z';await fs.writeFile(path.join(root,batch+'.checkpoint.json'),JSON.stringify({startedAt:'2026-10-08T01:47:11Z'}));assert.equal((await readSourceUpdate(root)).state,'unknown');const receipt={batchId:batch,mode:'daily-add-only',status:'complete',plannedCount:45,readbackVerifiedCount:45,unknownWriteCount:0,createdCount:0,recoveredWriteCount:45,sourceEvidence:{sourceRankedRows:500},finishedAt:'2026-10-08T01:51:14Z'};const p=path.join(root,batch+'.write-receipt.json');await fs.writeFile(p,JSON.stringify(receipt));assert.deepEqual(await readSourceUpdate(root),{state:'completed',completed:45,total:45,added:45,selected:500,observedAt:receipt.finishedAt});await fs.writeFile(p,JSON.stringify({...receipt,readbackVerifiedCount:44}));assert.equal((await readSourceUpdate(root)).state,'unknown');}finally{await fs.rm(root,{recursive:true,force:true})}});

test('connection loss is explicit without claiming logout or missing authorization',()=>{const p=publicStatus({...snapshot(),connectionState:'disconnected',sites:{chann:{state:'unknown'},buyin:{state:'unknown'}},component:'unknown'});assert.equal(p.connectionState,'disconnected');assert.equal(p.sites.buyin.state,'unknown');assert.equal(publicStatus({...snapshot(),connectionState:'secret'}).connectionState,undefined);});
